[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

# these lib and bin are not strictly required if kept to defaults
[lib]
path = "src/lib.rs"

# note double brackets - an array - you can have multiple bins, only 1 lib
# if requiring more lib use a Worspace
[[bin]]
path = "src/main.rs"
name = "zero2prod"

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

# for dependencies required for tests only
[dev-dependencies]
reqwest = "0.12"