[advisories]
ignore = [
    "RUSTSEC-2024-0320", 
    { id = "RUSTSEC-2024-0320", reason = "functionality works, this is not relevant" },
    "futures-util@0.3.30", # you can also ignore yanked crate versions if you wish
    { crate = "futures-util@0.3.30", reason = "This works" },
]
