# base.yaml
application:
  port: 8000

database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"

email_client:
  base_url: "http://localhost"
  sender_email: "postmaster@tomslocombe2.plus.com"
  auth_token: "my-secret-token"
  timeout_milliseconds: 10000