name: Security audit
on:
  push:
    branches: [main]
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '**/deny.toml'
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/install-action@cargo-deny
      - name: Init cargo deny
        run: cargo deny innit ~/deny.toml
      - name: Scan for vulnerabilities
        run: cargo deny check advisories
